version: "3.8"

services:
  backend:
    build: ./backend
    container_name: imec-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true #Hot Reload
      - DATABASE_URL=sqlite:///./sql_app.db

  frontend:
    build: ./frontend
    container_name: imec-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
